# Generated by Django 3.1.6 on 2021-02-04 14:35

import catalog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataload',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='thumbnails',
            new_name='small',
        ),
        migrations.AddField(
            model_name='doctor',
            name='source_id',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='source_file',
            field=models.ImageField(default=None, upload_to=catalog.models.get_image_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='source_id',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
