# Generated by Django 3.1.6 on 2021-02-04 15:34

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210204_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='full',
            field=models.ImageField(null=True, upload_to=catalog.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='large',
            field=models.ImageField(null=True, upload_to=catalog.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='small',
            field=models.ImageField(null=True, upload_to=catalog.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='source_file',
            field=models.ImageField(null=True, upload_to=catalog.models.get_image_path),
        ),
    ]
