# Generated by Django 3.1.6 on 2021-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210204_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='full_source_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='large_source_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='small_source_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='source_url',
            field=models.URLField(null=True),
        ),
    ]
